### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by Alex1326476156** [chinaheyu/chatgpt_ros#3]
请问，更新了apikey之后，不用编译就直接运行ros2 run chatgpt_ros chatgpt_action_server这一步吗？提示找不到包名，请问是否有添加依赖等步骤？

**Comment by lukehugh** [comment]
需要，参考步骤如下

```
cd <你的工作空间>
rosdep install --from-paths src -r -y --ignore-src
colcon build --symlink-install
source install/setup.bash            
```

**Comment by Alex1326476156** [comment]
感谢，我立刻试试！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月19日(周五) 晚上9:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chinaheyu/chatgpt_ros] 编译报错 (Issue #3)




 
需要，参考步骤如下
 cd <你的工作空间&gt; rosdep install --from-paths src -r -y --ignore-src colcon build --symlink-install source install/setup.bash

**Comment by Alex1326476156** [comment]
尊敬的作者，您好，不知是否打扰到您，我执行完这一步
colcon build --symlink-install，报错如下：
-----------------------------------------
***@***.***:~/test03$ colcon build --symlink-install
Starting &gt;&gt;&gt; chatgpt_ros_interfaces
--- stderr: chatgpt_ros_interfaces                             
Traceback (most recent call last):
  File "/home/alex/test03/build/chatgpt_ros_interfaces/ament_cmake_python/chatgpt_ros_interfaces/setup.py", line 4, in <module&gt;
    setup(
  File "/home/alex/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/alex/.local/lib/python3.10/site-packages/setuptools/dist.py", line 450, in __init__
    _Distribution.__init__(
  File "/usr/lib/python3.10/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/home/alex/.local/lib/python3.10/site-packages/setuptools/dist.py", line 827, in finalize_options
    for ep in sorted(loaded, key=by_order):
  File "/home/alex/.local/lib/python3.10/site-packages/setuptools/dist.py", line 826, in <lambda&gt;
    loaded = map(lambda e: e.load(), filtered)
  File "/home/alex/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2449, in load
    self.require(*args, **kwargs)
  File "/home/alex/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2472, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/alex/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (setuptools 58.0.2 (/home/alex/.local/lib/python3.10/site-packages), Requirement.parse('setuptools&gt;=62.4'))
gmake[2]: *** [CMakeFiles/ament_cmake_python_build_chatgpt_ros_interfaces_egg.dir/build.make:70：CMakeFiles/ament_cmake_python_build_chatgpt_ros_interfaces_egg] 错误 1
gmake[1]: *** [CMakeFiles/Makefile2:447：CMakeFiles/ament_cmake_python_build_chatgpt_ros_interfaces_egg.dir/all] 错误 2
gmake[1]: *** 正在等待未完成的任务....
gmake: *** [Makefile:146：all] 错误 2
---
Failed   <<< chatgpt_ros_interfaces [1.55s, exited with code 2]

Summary: 0 packages finished [2.04s]
  1 package failed: chatgpt_ros_interfaces
  1 package had stderr output: chatgpt_ros_interfaces
  2 packages not processed
--------------------------------------------------------------------------
网上找了很久，不清楚问题出在哪里，第一步的rosdep install --from-paths src -r -y --ignore-src运行是没有问题的。这次的报错和我第一次复现这个项目编译的过程中出现的错误是一样的。

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chinaheyu/chatgpt_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月19日(星期五) 晚上9:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chinaheyu/chatgpt_ros] 编译报错 (Issue #3)





 
需要，参考步骤如下
 cd <你的工作空间&gt; rosdep install --from-paths src -r -y --ignore-src colcon build --symlink-install source install/setup.bash

**Comment by lukehugh** [comment]
可能是你的环境有问题吧，我在foxy，humble，iron编译都是正常的。

以下是在docker编译的输出：

### ros:foxy

```
root@2b9560066a53:~/ros2_ws# colcon build --symlink-install
Starting >>> chatgpt_ros_interfaces
Finished <<< chatgpt_ros_interfaces [5.17s]
Starting >>> chatgpt_ros
Starting >>> chatgpt_ros_turtlesim
Finished <<< chatgpt_ros_turtlesim [0.50s]
Finished <<< chatgpt_ros [0.51s]

Summary: 3 packages finished [5.78s]
```

### ros:humble

```
root@3b180dc64d80:~/ros2_ws# colcon build --symlink-install
Starting >>> chatgpt_ros_interfaces
Finished <<< chatgpt_ros_interfaces [5.09s]
Starting >>> chatgpt_ros
Starting >>> chatgpt_ros_turtlesim
/usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'install-scripts' will not be supported in future versions. Please use the underscore name 'install_scripts' instead
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'install-scripts' will not be supported in future versions. Please use the underscore name 'install_scripts' instead
  warnings.warn(
--- stderr: chatgpt_ros_turtlesim
/usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
Finished <<< chatgpt_ros_turtlesim [0.84s]
--- stderr: chatgpt_ros
/usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
Finished <<< chatgpt_ros [0.90s]

Summary: 3 packages finished [6.49s]
  2 packages had stderr output: chatgpt_ros chatgpt_ros_turtlesim
```

### ros:iron

```
root@9d3da62e5049:~/ros2_ws# colcon build --symlink-install
Starting >>> chatgpt_ros_interfaces
Finished <<< chatgpt_ros_interfaces [6.77s]
Starting >>> chatgpt_ros
Starting >>> chatgpt_ros_turtlesim
/usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'install-scripts' will not be supported in future versions. Please use the underscore name 'install_scripts' instead
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'install-scripts' will not be supported in future versions. Please use the underscore name 'install_scripts' instead
  warnings.warn(
--- stderr: chatgpt_ros
/usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
Finished <<< chatgpt_ros [1.08s]
--- stderr: chatgpt_ros_turtlesim
/usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
Finished <<< chatgpt_ros_turtlesim [1.08s]

Summary: 3 packages finished [8.41s]
  2 packages had stderr output: chatgpt_ros chatgpt_ros_turtlesim
```
